Just updating
openupglobal/Blender-Chinese-Translation-Project pull request #6
Opened 2020-02-21 00:24 UTC by Okanegahoshi

把重復改成重複
把"Freestyle line style, reusable by multiple line sets"譯文中Freestyle缺少的t補上
加上冒號、刪除冒號
將...替換為全形字元……
將框選統一為方框選取、圈選統一為圓圈選取，以與套索選取統一格式
取消鍵盤專有名詞翻譯 (如：PageUp、PageDown)
……以及大量修正

*算圖並未修改成算繪，我想先取得社群共識再以Ctrl+F取代

2020-02-21 04:27 UTC, openup-global reviewed
修正很多地方! 目前有一個地方，我有點困惑，想知道這個 Tab 為什麼改成「\」? 一般可能是翻成「分頁」?

2020-02-21 04:27 UTC, openup-global commented on zh_TW.po
> +msgstr "\\"
@Okanegahoshi  想知道這個 Tab 為什麼改成「\\」? 一般可能是翻成「分頁」?

```suggestion
msgstr "分頁"
```

2020-02-21 04:30 UTC, Okanegahoshi commented
應該是誤按，無視就好

openup-global <notifications@github.com> 於 2020年2月21日 週五 12:27 寫道：

> *@openup-global* commented on this pull request.
>
> 修正很多地方! 目前有一個地方，我有點困惑，想知道這個 Tab 為什麼改成「\」? 一般可能是翻成「分頁」?
> ------------------------------
>
> In zh_TW.po
> <https://github.com/openupglobal/Blender-Chinese-Translation-Project/pull/6#discussion_r382390623>
> :
>
> >  msgid "Tab"
>
> -msgstr "標籤"
>
> +msgstr "\\"
>
>
> @Okanegahoshi <https://github.com/Okanegahoshi> 想知道這個 Tab 為什麼改成「\」?
> 一般可能是翻成「分頁」?
> ⬇️ Suggested change
>
> -msgstr "\\"
>
> +msgstr "分頁"
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/openupglobal/Blender-Chinese-Translation-Project/pull/6?email_source=notifications&email_token=AHZGDGJZTDBIKIRJPJE2SITRD5J3DA5CNFSM4KYZUGZKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCWM2TPY#pullrequestreview-362391999>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AHZGDGN5O7ITG7GXVRHQLQTRD5J3DANCNFSM4KYZUGZA>
> .
>

2020-02-24 06:18 UTC, stansu requested changes

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "工作區"
我覺得space翻成空間比較合適，區這個字留給area。

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "F 曲線修改器集合"
F想翻譯成函式

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr ""
先用MPEG-4 (divx)？

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "對比位元率"
constant應該是不變的意思吧？

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "觀測無損"
Perceptually在這裡的意思應該是人眼察覺

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "力集合"
force在特效模擬時比較常翻譯為外力

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr ""
這裡好像也是滾輪向下

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "左Ctrl"
ctrl翻成控制鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr ""
左控制鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "左Alt"
alt翻成轉換鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "左Shift"
shift是換檔鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "應用程式"
應用程式鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr ""
應用程式鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr ""
退出鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr ""
製表鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr ""
確認鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "左箭頭"
向左鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "下箭頭"
向下鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "右箭頭"
向右鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "上箭頭"
向上鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr ""
暫停鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr ""
插入鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr ""
插入鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
>  msgstr "上翻頁"
上頁鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
>  msgstr "下翻頁"
下頁鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr ""
結尾鍵

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "當選擇「陣列/向量」類型時 (位置、旋轉、色彩……等)，使用整個陣列"
…是否用1個就夠了？

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "選取方框"
應該是方框選取

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "選取圓圈"
圓圈選取

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "選取套索"
套索選取

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "時機"
這裡的timing指的好像不是時機

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "鍵幀設定"
keyframe我想翻成關鍵格
https://zh.wikipedia.org/wiki/%E9%97%9C%E9%8D%B5%E6%A0%BC

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "自動鍵幀處理"
自動設定關鍵格

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "文字算圖"
這裡遇到一個有趣的地方，Text Rendering #5

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "\\"
https://zh.wikipedia.org/wiki/%E5%88%86%E9%A0%81_(GUI)

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "全域影響"
全域偏好設定

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr ""
在此視圖顯示註解

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "主題偏好設定："
：要去掉嗎？

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "群集個體："
我想翻成群

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "循環："
賽寇士

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "匯出網格："
mesh我想翻成網面

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "晶格："
格塊

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "調焦 %d:%d"
這裡的功能應該是縮放的意思

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "無作用中鍵"
keying應該不能翻成“鍵”

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "添加與替換……"
尋找與取代

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "算圖音訊……"
聲音與繪圖無關，這裡的render要怎麼翻？ #5

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "大綱管理器資料操作……"
重複最後操作…

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "選取樣式……"
這裡pattern指的是物件名稱的模式

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "設為代理……"
這裡的make我建議翻為“做成”

2020-02-24 06:18 UTC, stansu commented on zh_TW.po
> +msgstr "設為區域……"
做成非外部連結

2020-02-29 02:46 UTC, Okanegahoshi commented on zh_TW.po
> +msgstr "工作區"
好

2020-02-29 02:47 UTC, Okanegahoshi commented on zh_TW.po
> +msgstr ""
沒翻譯的就會自動顯示原文 要寫一樣的東西不如不寫吧

2020-02-29 02:49 UTC, Okanegahoshi commented on zh_TW.po
> +msgstr "觀測無損"
對 查了一下 的確是人眼

2020-02-29 02:54 UTC, Okanegahoshi commented on zh_TW.po
> +msgstr "F 曲線修改器集合"
根據維基百科 這個F是Function 所以我還是先留著F好了

2020-02-29 02:56 UTC, Okanegahoshi commented on zh_TW.po
> +msgstr "設為區域……"
Make似乎沒辦法做統一翻譯
話說這個應該是「作」吧，「做」比較像Do the thing

2020-02-29 03:00 UTC, Okanegahoshi commented on zh_TW.po
> +msgstr "設為代理……"
好啊 先跟Set分開再說

2020-02-29 03:03 UTC, Okanegahoshi commented on zh_TW.po
> +msgstr "選取樣式……"
那我先把Pattern都翻成模式 把樣式留出去

2020-02-29 03:05 UTC, Okanegahoshi commented on zh_TW.po
> +msgstr "選取樣式……"
仔細想想這樣又會跟物件模式搞混 有點麻煩

2020-02-29 03:13 UTC, Okanegahoshi commented on zh_TW.po
> +msgstr "選取樣式……"
等等直接打開看Pattern寫在哪裡好了 看怎樣會搞混怎樣不會

2020-02-29 12:12 UTC, stansu commented on zh_TW.po
> +msgstr "F 曲線修改器集合"
function你想怎麼翻？

2020-02-29 12:13 UTC, stansu commented on zh_TW.po
> +msgstr ""
OK

2020-02-29 12:21 UTC, stansu commented on zh_TW.po
> +msgstr "選取樣式……"
我覺得可以翻成“以文字選取物件”

2020-02-29 12:32 UTC, stansu commented on zh_TW.po
> +msgstr "設為區域……"
「作」和「做」都有「從事」義。涉及具體的事物，習慣寫「做」，涉及抽象的事物，習慣寫「作」。

原文網址：https://kknews.cc/culture/b5yomp6.html

2020-03-05 07:38 UTC, bisechen commented on zh_TW.po
> +msgstr "F 曲線修改器集合"
> F想翻譯成函式

F 根據熟手說的，這個字就是函數的意思，個人建議直接翻成函數就好了，例如「動作函數曲線」，不管看起來或念出來都很順。

2020-03-05 07:45 UTC, bisechen commented on zh_TW.po
> +msgstr "算圖音訊……"
Render 這個字有「呈現」的意思，聲音的話不妨往這方面去評估～^^

2020-03-06 13:29 UTC, bisechen commented on zh_TW.po
> +msgstr "左Ctrl"
鍵盤文字的部分建議就依照原樣，不然可能反而看不懂了...

2020-03-12 12:34 UTC, stansu commented on zh_TW.po
> +msgstr "左Shift"
建議切換鍵

2020-03-18 06:45 UTC, stansu commented
已merge

2020-03-18 06:45 UTC, closed without merging